lang: zh-cn
title: å®‰é“ğŸ’–é›†é‚®
email: andor.chen.27@gmail
baseurl: "/stamps"
url: "https://andorchen.github.io"

exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'tmp']
include:
  - _pages
keep_files: ['.git', '.nojekyll']
timezone: '+0800'

# just-the-docs theme settings
theme: just-the-docs
callouts:
  warning:
    title: è­¦å‘Š
    color: red
  note:
    title: è¯´æ˜
    color: green

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "_pages"
    values:
      permalink: /:basename/
      layout: 'page'

markdown: ACKramdownParser

collections:
  - notes
