lang: zh-cn
title: å®‰é“ğŸ’–é›†é‚®
email: andor.chen.27@gmail
baseurl: "/stamps" # the subpath of your site, e.g. /blog
url: "https://about.ac/stamps/" # the base hostname & protocol for your site, e.g. http://example.com

# just-the-docs theme settings
theme: just-the-docs
callouts:
  warning:
    title: è­¦å‘Š
    color: red
  note:
    title: è¯´æ˜
    color: green

plugins:
  - jekyll-feed

exclude:
  - Rakefile
  - README.md

include:
  - _pages

defaults:
  -
    scope:
      path: "_pages"
    values:
      permalink: /:basename/
      layout: 'page'

markdown: ACKramdownParser
